---
- name: Install Dependencies for Maven Projects
  hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        pkg:
          - openjdk-11-jdk
          - maven
        state: present

- name: Set default JAVA_HOME
  hosts: localhost
  become: true
  tasks:
    - name: Set System JAVA_HOME
      blockinfile:
        path: "/etc/environment"
        marker_begin: "BEGIN JAVAHOME"
        marker_end: "END JAVAHOME"
        block: |
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
